---
- hosts: all
  remote_user: root

  - name: copy Docker Compose file
      copy:
        src: /root/Docker-App
        dest: /
      loop:
      - docker-compose.yml
      

    # use files parameter to use multiple docker-compose.yml files
    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /
        files:
          - docker-compose.yml